name: Trivy DB
on:
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  build:
    name: Build DB
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install bbolt
      run: go get -v github.com/etcd-io/bbolt/cmd/bbolt

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Prepare dirs
      run: mkdir cache assets

    - name: Download vuln-list
      run: |
        wget --quiet https://github.com/aquasecurity/vuln-list/archive/master.zip
        unzip -q master.zip
        mv vuln-list-master cache/vuln-list

    - name: Clone advisories
      run: |
        git clone --depth 1 https://github.com/rubysec/ruby-advisory-db.git cache/ruby-advisory-db
        git clone --depth 1 https://github.com/RustSec/advisory-db.git cache/rust-advisory-db
        git clone --depth 1 https://github.com/FriendsOfPHP/security-advisories cache/php-security-advisories
        git clone --depth 1 https://github.com/nodejs/security-wg.git cache/nodejs-security-wg
        git clone --depth 1 https://github.com/pyupio/safety-db.git cache/python-safety-db

    - name: Build the binary
      run: go build -o trivy-db cmd/trivy-db/main.go

    #
    # Full DB
    #
    - name: Build full database
      run: ./trivy-db build --cache-dir ./cache --update-interval 12h

    - name: Compact DB
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        bbolt compact -o assets/trivy.db cache/db/trivy.db
        rm cache/db/trivy.db

    #
    # Light DB
    #
    - name: Build light database
      run: ./trivy-db build --light --cache-dir ./cache --update-interval 12h

    - name: Compact DB
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        bbolt compact -o assets/trivy-light.db cache/db/trivy.db

    #
    # Upload
    #
    - name: Compress assets
      run: gzip assets/*

    - name: Upload assets
      run: ./trivy-db upload --dir assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_OWNER: mozillazg

